### ISSUE TITLE
Violin + box plot

### ISSUE THREAD

**Issue by dvzacharycutler** [datavisyn/visyn_core#48]
Features:

- [ ] requires aggregation, arquero 
- [ ] Switch between violin + box plot + both
- [ ] Selection - show individual points until you have enough to draw another violin
- [ ] N selections for both numerical + categorical
- [ ] Violin halves

Resources:
https://d3-graph-gallery.com/violin.html

-----------------------------

### Tasks
- [ ] https://github.com/datavisyn/bioinsight/issues/359
- [ ] https://github.com/datavisyn/bioinsight/issues/364
- [ ] https://github.com/datavisyn/bioinsight/issues/365
- [ ] Add ability to sort axis (https://github.com/datavisyn/bioinsight/issues/363)
- [ ] https://github.com/datavisyn/bioinsight/issues/362
- [ ] https://github.com/datavisyn/bioinsight/issues/361
- [ ] Allow color assignment via config (https://github.com/datavisyn/reprovisyn/issues/1171)
- [ ] X-axis labels should be rotated by 180° and truncated
- [x] ~~The dropdowns in the sidebar don't scroll - if there's a long list of options, it is cut off and there is no possibility to see them anymore~~
- [x] ~~When having multiples, the tick and axis labels overflow with the next chart (see screenshot)~~
- [x] ~~When having multiples, the axis labes get very small, but the tick labels remain the same size (see screenshot)~~
![image](https://github.com/datavisyn/visyn_core/assets/57343176/ac744e4c-b11a-49c0-bf16-ac87965b586e)
