### ISSUE TITLE
EPIC: Scatter plot issues

### ISSUE THREAD

**Issue by thinkh** [datavisyn/visyn_core#522]
```[tasklist]
### Tasks
- [ ] https://github.com/datavisyn/visyn_core/issues/470
- [ ] https://github.com/datavisyn/communication_bi_ordino/issues/76
- [x] Improve brush performance for 40+k points with and without facets
- [x] Do not reset zoom and pan position when switching between brush and pan + zoom tool
- [x] Double-click on empty space should deselect all
- [ ] Slight offset for tooltip from cursor
- [ ] ~~Debounce tooltip (?)~~
- [ ] https://github.com/datavisyn/visyn_core/issues/471
```
